spring:
  application:
    name: FriendyBeApplication
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: friendy
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true

friendy:
  community:
    server:
      url: ${SERVER_URL}

jwt:
  access:
    secret: ${TOKEN_SECRET_KEY}
    expiration: 1800000 # 30분

  refresh:
    secret: ${TOKEN_SECRET_KEY}
    expiration: 86400000 # 1일
